spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: task-tracker-group

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true